name: Jessye Pereira

on:
  schedule: # executa a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch: # permite executar manualmente

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: JessyeKessia
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publish the result using GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
