name: Update Snake GIF

on:
  schedule:
    - cron: "* */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  build:
    name: Update Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Gera o GIF da cobrinha com base nos commits
      - name: Generate Snake GIF
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: JessyeKessia
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica o GIF no GitHub Pages
      - name: Publish GIF to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
